### ISSUE TITLE
Rico version is not shown correctly in banner

### ISSUE THREAD

**Issue by madmas** [rico-projects/rico#156]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Rico or Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**
During startup in a SpringBoot application, Rico prints out an ANSI banner that should also contain it's version, but it shows only `$version`.

<img width="609" alt="grafik" src="https://user-images.githubusercontent.com/37251/87171001-64e6f600-c2d2-11ea-9005-a3812d02c46c.png">

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [x]  Fork the repository in github by simply clicking the 'fork' button.
- [x]  Check out the forked repository
- [x]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [x]  Commit your changes.
- [x]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by grigala** [comment]
I don't think value references can work across `.properties` files - those values are simple strings.
The version number should be declared in a project level `build.properties` file:
https://github.com/rico-projects/rico/blob/52f351db780c5dd6e8aa178fa6548649af5f076e/base/rico-core/src/main/resources/build.properties#L18

`version=2.1.0-SNAPSHOT`

P.S. the same applies to `buildDate=$buildDate` and `buildTime=$buildTime`.
