### ISSUE TITLE
External repository links for client library implementations in README are pointing to a wrong URL

### ISSUE THREAD

**Issue by grigala** [rico-projects/rico#173]
**🆕🐥 First Timers Only**

This issue is reserved for people who never contributed to Rico or Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

In the [README.md#L34-L37](https://github.com/rico-projects/rico/edit/master/README.md#L34) external repository links for JavaScript, Polymer 2, AngularJS and Angular are pointing to the wrong URL. They all point to:
 `https://github.com/rico-project/$REPO_NAME` the correct URL is:
 `https://github.com/rico-projects/$REPO_NAME`

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [x]  Fork the repository in Github by simply clicking the 'fork' button.
- [x]  Check out the forked repository
- [x]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [x]  Commit your changes.
- [x]  Start a Pull Request.
- [x]  Done 👍 Ask in comments for a review :)
- [x]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [x]  You did it 🎉 We will merge the fix in the master branch.
- [x]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by acasadoquijada** [comment]
Hi, I would like to work on this issue, can you assign it to me?

**Comment by sclassen** [comment]
Sure go ahead
