### ISSUE TITLE
Rico-Angular: Instanciating multiple controllers "at the same time" mixes up the model references

### ISSUE THREAD

**Issue by madmas** [rico-projects/rico#46]
When multiple controllers are created "at the same time", meaning timely very close to eeach other, the model references of these controllers are mixed up.

Some investigation has shown that this is related to the `highlanderPM` used in RicoJS tohandle model instanciation. (see https://github.com/rico-projects/rico-js/blob/29f12ed97c1701b77b2c8e0beecca8576f39bdcd/src/remoting/controllerManager.js#L53) .

**Comment by hendrikebbers** [comment]
I think the best way to fix this is by changing the command batching. Any command that is not a value change command should mark the end of a batch for commands that can be send to the server.

**Comment by hendrikebbers** [comment]
Removed Angular Label since this is a general JS problem

**Comment by madmas** [comment]
@hendrikebbers I think these comments belong into #47 or would be seperate issues, first we should adress a fix locally.

**Comment by madmas** [comment]
Fixed in Rico-Angular by https://github.com/rico-projects/rico-angular/pull/7
